<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class FacilityInfrastructure extends Model
{
   use HasFactory;
   protected $table = 'facility_infrastructure';    
   protected $fillable = [
'facility_information_id',
'departmental_waiting_bay',
'departmental_waiting_bay_remarks',
'reception_registration_area',
'reception_registration_area_remarks',
'triage_area',
'triage_area_remarks',
'health_information_system',
'health_information_system_remarks',
'consultation_rooms_with_mackintosh',
'consultation_rooms_with_mackintosh_remarks',
'treatment_rooms',
'treatment_rooms_remarks',
'minor_theatre',
'minor_theatre_remarks',
'nurse_station',
'nurse_station_remarks',
'staff_lounge',
'staff_lounge_remarks',
'resource_centre',
'resource_centre_remarks',
'orthopedic_room',
'orthopedic_room_remarks',
'dental_unit',
'dental_unit_remarks',
'nursing_incharge_office',
'nursing_incharge_office_remarks',
'counselling_room',
'counselling_room_remarks',
'hand_wash_basin',
'hand_wash_basin_remarks',
'accident_emergency_department',
'accident_emergency_department_remarks',
'clinic_paediatrics',
'clinic_paediatrics_remarks',
'clinic_internal_medicine',
'clinic_internal_medicine_remarks',
'clinic_gynaecology',
'clinic_gynaecology_remarks',
'clinic_high_risk_obstetric',
'clinic_high_risk_obstetric_remarks',
'clinic_surgical_orthopaedic_ent',
'clinic_surgical_orthopaedic_ent_remarks',
'clinic_mental_health',
'clinic_mental_health_remarks',
'clinic_ophthalmology',
'clinic_ophthalmology_remarks',
'clinic_dermatology',
'clinic_dermatology_remarks',
'clinic_tb_hiv_chronic',
'clinic_tb_hiv_chronic_remarks',
'mch_anc_room',
'mch_anc_room_remarks',
'mch_fp_room',
'mch_fp_room_remarks',
'mch_cwc_room',
'mch_cwc_room_remarks',
'mch_immunization_room',
'mch_immunization_room_remarks',
'mch_nutrition_room',
'mch_nutrition_room_remarks',
'mch_waiting_bay',
'mch_waiting_bay_remarks',
'imaging_xray',
'imaging_xray_remarks',
'imaging_opg',
'imaging_opg_remarks',
'imaging_mammography',
'imaging_mammography_remarks',
'imaging_ultrasound',
'imaging_ultrasound_remarks',
'imaging_ct_scan',
'imaging_ct_scan_remarks',
'imaging_mri',
'imaging_mri_remarks',
'imaging_fluoroscopy',
'imaging_fluoroscopy_remarks',
'imaging_image_intensifier',
'imaging_image_intensifier_remarks',
'renal_dialysis_unit',
'renal_dialysis_unit_remarks',
    ];
}
